import requests
armors = ["SUPERIOR_DRAGON_CHESTPLATE","SUPERIOR_DRAGON_LEGGINGS","SUPERIOR_DRAGON_BOOTS","FAIRY_BOOTS","LEAFLET_CHESTPLATE","LEAFLET_LEGGINGS","LEAFLET_BOOTS","FAIRY_LEGGINGS","FAIRY_CHESTPLATE","CRYSTAL_BOOTS","CRYSTAL_LEGGINGS","CRYSTAL_CHESTPLATE","CHESTPLATE_OF_THE_PACK","LAPIS_ARMOR_CHESTPLATE","LAPIS_ARMOR_LEGGINGS","LAPIS_ARMOR_BOOTS","GROWTH_HELMET","GROWTH_CHESTPLATE","GROWTH_LEGGINGS","GROWTH_BOOTS","CHEAP_TUXEDO_BOOTS","CHEAP_TUXEDO_LEGGINGS","CHEAP_TUXEDO_CHESTPLATE","BLAZE_CHESTPLATE","BLAZE_LEGGINGS","BLAZE_BOOTS","SPONGE_BOOTS","SPONGE_LEGGINGS","SPONGE_CHESTPLATE","PUMPKIN_HELMET","PUMPKIN_CHESTPLATE","PUMPKIN_LEGGINGS","PUMPKIN_BOOTS","YOUNG_DRAGON_CHESTPLATE","YOUNG_DRAGON_LEGGINGS","YOUNG_DRAGON_BOOTS","STRONG_DRAGON_CHESTPLATE","STRONG_DRAGON_LEGGINGS","STRONG_DRAGON_BOOTS","WISE_DRAGON_CHESTPLATE","WISE_DRAGON_LEGGINGS","WISE_DRAGON_BOOTS","UNSTABLE_DRAGON_CHESTPLATE","UNSTABLE_DRAGON_LEGGINGS","UNSTABLE_DRAGON_BOOTS","OLD_DRAGON_CHESTPLATE","OLD_DRAGON_LEGGINGS","OLD_DRAGON_BOOTS","PROTECTOR_DRAGON_CHESTPLATE","PROTECTOR_DRAGON_LEGGINGS","PROTECTOR_DRAGON_BOOTS","TARANTULA_HELMET","TARANTULA_LEGGINGS","ANGLER_CHESTPLATE","ANGLER_LEGGINGS","ANGLER_BOOTS","SQUID_BOOTS","BAT_PERSON_CHESTPLATE","BAT_PERSON_LEGGINGS","BAT_PERSON_BOOTS","FARMER_BOOTS","RANCHERS_BOOTS","FARM_SUIT_HELMET","FARM_SUIT_CHESTPLATE","FARM_SUIT_LEGGINGS","FARM_SUIT_BOOTS","FARM_ARMOR_HELMET","FARM_ARMOR_CHESTPLATE","FARM_ARMOR_LEGGINGS","FARM_ARMOR_BOOTS","SPEEDSTER_HELMET","SPEEDSTER_CHESTPLATE","SPEEDSTER_LEGGINGS","SPEEDSTER_BOOTS","CACTUS_HELMET","CACTUS_CHESTPLATE","CACTUS_LEGGINGS","CACTUS_BOOTS","MINER_OUTFIT_HELMET","MINER_OUTFIT_CHESTPLATE","MINER_OUTFIT_LEGGINGS","MINER_OUTFIT_BOOTS","MUSIC_PANTS","MUSHROOM_HELMET","MUSHROOM_CHESTPLATE","MUSHROOM_LEGGINGS","MUSHROOM_BOOTS","GUARDIAN_CHESTPLATE","CREEPER_LEGGINGS","EMERALD_ARMOR_HELMET","EMERALD_ARMOR_CHESTPLATE","EMERALD_ARMOR_LEGGINGS","EMERALD_ARMOR_BOOTS","OBSIDIAN_CHESTPLATE","ARMOR_OF_MAGMA_HELMET","ARMOR_OF_MAGMA_CHESTPLATE","ARMOR_OF_MAGMA_LEGGINGS","ARMOR_OF_MAGMA_BOOTS"]

with open("defaults.txt", "r") as r:
  defaultHexes = r.readlines()
  
for armor in armors:
  matches = ["UNDYED"]
  for i in defaultHexes:
    if armor in i.strip():
      matches.append((i[i.find(" ") + 1:]).strip())
  armorID = armor
  
  hexList = requests.get("https://api.tem.cx/armour/find_hexes?itemId=" + armorID + "&key=01bd98b3-d60d-4401-9a50-8b5ed39fa60a").json()
  
  for i in range(len(hexList['hexes'])):
    currentHex = hexList['hexes'][i]['hex']
    if currentHex.upper() in matches:
      print("SKIPPING " + str(currentHex.upper()) + " " + armorID)
      continue
    else:
      ownersList = requests.get("https://api.tem.cx/armour/find_owners?hexCode=" + currentHex + "&itemId=" + armorID + "&key=PUT KEY HERE THANKS").json()
      for j in range(len(ownersList['armour'])):
        with open("newdb.txt", "a") as a:
          print(armorID + "|" + str(currentHex.upper()) + "," + str(ownersList['armour'][j]['owner']['playerUuid']) + "*" + str(ownersList['armour'][j]['owner']['profileUuid']) + "\n")
          a.write(armorID + "|" + str(currentHex.upper()) + "," + str(ownersList['armour'][j]['owner']['playerUuid']) + "*" + str(ownersList['armour'][j]['owner']['profileUuid']) + "\n")
